name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'ytanck/interview-reference'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      
      # # Create Docker Image in Github
      # - name: Login to the GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push image:latest
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/jaywcjlove/reference:latest

      # - name: Build and push image:tags
      #   uses: docker/build-push-action@v3
      #   if: steps.create_tag.outputs.successful
      #   with:
      #     push: true
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/jaywcjlove/reference:${{steps.changelog.outputs.version}}

      # # Create Docker Image in Github
      # - name: Login to GitHub registry
      #   run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Build docker image
      #   run: docker build -t ghcr.io/jaywcjlove/reference:latest .

      # - name: Publish to GitHub registry
      #   run: docker push ghcr.io/jaywcjlove/reference:latest

      # - name: Tag docker image (beta) and publish to GitHub registry
      #   if: steps.create_tag.outputs.successful
      #   run: |
      #     echo "version: v${{ steps.changelog.outputs.version }}"
      #     docker tag ghcr.io/jaywcjlove/reference:latest ghcr.io/jaywcjlove/reference:${{steps.changelog.outputs.version}}
      #     docker push ghcr.io/jaywcjlove/reference:${{steps.changelog.outputs.version}}

      # # Create Docker Image
      # - name: Docker login
      #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build reference image
      #   run: docker image build -t reference .

      # - name: Tags & Push image(latest)
      #   run: |
      #     echo "DOCKER_USER: ${{ secrets.DOCKER_USER }}"
      #     docker tag reference ${{ secrets.DOCKER_USER }}/reference:latest
      #     docker push ${{ secrets.DOCKER_USER }}/reference:latest

      # - name: Tags & Push image
      #   if: steps.create_tag.outputs.successful
      #   run: |
      #     echo "outputs.tag - ${{ steps.changelog.outputs.version }}"
      #     docker tag reference ${{ secrets.DOCKER_USER }}/reference:${{steps.changelog.outputs.version}}
      #     docker push ${{ secrets.DOCKER_USER }}/reference:${{steps.changelog.outputs.version}}
